<template>
  <div class="signin">
    <div id="app_signin">
      <nav class="navigation">
        <img src="../assets/icon-left-font-monochrome-black.png" alt="Logo Grupomania" class="logoGrupomania">
      </nav>
      <p class="signin-headline">Sign in</p>
      <div class="signin_form" method="post">
        <div class="email_input-login">
          <label for="email"></label>
          <input type="text" id="email" name="email" v-model="dataForm.email" placeholder="Email" required>
        </div>
        <div class="password_input-login">
          <label for="password"></label>
          <input type="password" id="password" name="password" v-model="dataForm.password" placeholder="Password"
            required>
        </div>
        <div class="login_btn">
          <button @click.prevent="SignIn()" class="btn_li">Log in</button>
          <p id="errorMsg"></p>
        </div>
      </div>
      <div class="links">
        <p>Don't have an account?</p>
        <router-link to="/signup" class="signUp">Sign up</router-link>
      </div>
    </div>
  </div>
</template>
<script>

import store from '../store/index.js'
import router from '../router'

export default {
  name: 'Login',

  data() {
    return {
      dataForm: {
        firstname: null,
        lastname: null,
        email: null,
        password: null,
        idUser: null
      },
    }
  },
  methods: {
    SignIn() {

      //Values ​​from form to data object
      const data = {
        ...this.dataForm
      }
      if (
        this.dataForm.email !== null ||
        this.dataForm.password !== null
      ) {
        fetch('http://localhost:3000/api/users/login',
          {
            method: 'POST',
            mode: 'cors',
            headers: {
              'Content-Type': 'application/json',
              'Accept': 'application/json'
            },
            body: JSON.stringify(data)
          }
        )
          .then(res => {
            const localData = res;
            store.state.isLogged = true;
            localData.json()
              .then(data => {
                //Retreiving the values in localStorage generated by the token
                localStorage.setItem('token', data.token)
                localStorage.setItem('idUser', data.idUser)
                this.firstname = data.firstname;
                this.lastname = data.lastname;
                this.idUser = data.idUser;
              })

            //If the request is successfull
            if (res.status === 200) {
              window.location.href = "ProfilePage"
            } else {
              const errMsg = document.getElementById('errorMsg');
              errMsg.innerHTML = "<p>Incorrect email or password<p>"
            }
          })
          .catch(error => { console.error(error) })
      }
    }
  }
}
</script>

<style lang="scss">
//Colors
@import '../styles/variables';

//Mixins
@import '../styles/mixins-login';

.signin {
  @include signin;
}

.signin-headline {
  @include signin-headline;
}

.signin_form {
  @include signin_form;
}

.email_input-login {
  @include email_input-login;
}

.password_input-login {
  @include password_input-login;
}

.login_btn {
  @include login_btn;
}

.links {
  @include links;
}
</style>